teams_and_ids = {'Los Angeles Angels': 108,
                 'Arizona Diamondbacks': 109,
                 'Baltimore Orioles': 110,
                 'Boston Red Sox': 111,
                 'Chicago Cubs': 112,
                 'Cincinnati Reds': 113,
                 'Cleveland Indians': 114,
                 'Colorado Rockies': 115,
                 'Detroit Tigers': 116,
                 'Houston Astros': 117,
                 'Kansas City Royals': 118,
                 'Los Angeles Dodgers': 119,
                 'Washington Nationals': 120,
                 'New York Mets': 121,
                 'Oakland Athletics': 133,
                 'Pittsburgh Pirates': 134,
                 'San Diego Padres': 135,
                 'Seattle Mariners': 136,
                 'San Francisco Giants': 137,
                 'St. Louis Cardinals': 138,
                 'Tampa Bay Rays': 139,
                 'Texas Rangers': 140,
                 'Toronto Blue Jays': 141,
                 'Minnesota Twins': 142,
                 'Philadelphia Phillies': 143,
                 'Atlanta Braves': 144,
                 'Chicago White Sox': 145,
                 'Miami Marlins': 146,
                 'New York Yankees': 147,
                 'Milwaukee Brewers': 158}
